[workspace]
resolver = "2"
members = [
    "courses/cli-salad",
    "courses/data-race",
    "courses/graph-centrality-ufc",
    "courses/hashmap-count",
    "courses/hashmap-language",
    "courses/btreeset-fruit",
    "courses/hashset-fruit",
    "courses/linked-list-fruit-salad",
    "courses/vector-fruit-salad"
, "courses/binaryheap-fruit", "courses/pagerank", "courses/lisbon-shortest-path", "courses/community-detection", "courses/graph-visualize", "courses/challange-week1", "courses/mutable-fruit-salad", "courses/cli-customize-fruit-salad"]


[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ii"]
license = "MIT"


[workspace.dependencies]
tracing = "0.1"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
panic = "abort"

[profile.dev]
debug = 1
incremental = true

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
